apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-equipment-ufe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: hospital-equipment-ufe-label
  template:
    metadata:
      labels:
        pod: hospital-equipment-ufe-label
    spec:
      containers:
        - name: hospital-equipment-ufe-container
          image: martinabillich/wac-hospital-equipment
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "32M"
              cpu: "0.1"
            limits:
              memory: "320M"
              cpu: "0.3"
