apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: m-nem-ambulance-webapi
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: wac-hospital
  rules:
  - http:
      paths:
      - path: /m-nem-waiting-list-api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: m-nem-ambulance-webapi
            port:
              name: webapi-s-port
