apiVersion: apps/v1
kind: Deployment
metadata:
  name: tl-team-ufe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        pod: tl-team-ufe-label
  template:
    metadata:
      labels: 
        pod: tl-team-ufe-label
    spec:
      containers:
      - name: tl-team-ufe-container
        image: timolabsky/wac-equipment-fe:0.0.1-31
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:                   
            requests:               
                memory: "32M"
                cpu: "0.1"
            limits:
                memory: "320M"
                cpu: "0.3"
