apiVersion: apps/v1
kind: Deployment
metadata:
  name: mf-ambulance-ufe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        pod: mf-ambulance-ufe-label                        
  template:                   
    metadata:
      labels: 
        pod: mf-ambulance-ufe-label
    spec:
      containers:
      - name: mf-ambulance-ufe-container 
        image: mfranczel/ambulance-ufe:1.0.0-14
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:                 
            requests:               
                memory: "32M"
                cpu: "0.1"
            limits:
                memory: "320M"
                cpu: "0.3"
