apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../_msevcik_demo
  - ../../pc_ambulance
  - ../../md_ambulance
  - ../../mar-ku-ambulance
  - ../../xholubov_ambulance

namespace: wac-hospital
