apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../_msevcik_demo
  - ../../ab-ambulance
  - ../../anbe-ambulance
  - ../../ac-ambulance
  - ../../adp-team
  - ../../af-mb-team
  - ../../af-ambulance
  - ../../bado-ambulance
  - ../../bamat-ambulance
  - ../../bbm-team
  - ../../db_ambulance
  - ../../fa-ambulance
  - ../../fa-projekt
  - ../../fchalas-ambulance
  - ../../fp-sz-team
  - ../../hhh-team
  - ../../hianikova-ambulance
  - ../../hoka-ambulance
  - ../../hord-team
  - ../../hud-nem-team
  - ../../ij-ambulance
  - ../../ij-jj-hospital-warehouse
  - ../../janec-ambulance
  - ../../jb_ambulance
  - ../../jbl-project
  - ../../jj-ambulance
  - ../../jm-lm-ambulance
  - ../../jv-team
  - ../../kali-team
  - ../../kk-ambulance
  - ../../ll-ambulance
  - ../../m-nem-ambulance
  - ../../mar-ku-ambulance
  - ../../mb-ambulance
  - ../../md_ambulance
  - ../../mdurovic-ambulance
  - ../../mf-ambulance
  - ../../mf-project
  - ../../mimast-team
  - ../../mjankuliak-ambulance
  - ../../mkrchnavy-ambulance
  - ../../mkukucka-ambulance
  - ../../mkukucka-covid19-testing-administration
  - ../../pablo-ambulance
  - ../../pc-ambulance
  - ../../pm-ambulance
  - ../../xkollarovap-project
  - ../../peter-plevko

  - ../../pirky
  - ../../pkollarova-ambulance
  - ../../pprerko-team
  - ../../rericha_ambulance
  - ../../stesch-ambulance
  - ../../team09-form-app
  - ../../t13-ambulance
  - ../../tech-podolae-ambulance
  - ../../tl-team
  - ../../vf_ambulance
  - ../../xglemba-project
  - ../../xholubov_ambulance
  - ../../xvykopal-ambulance
  - ../../zy-ambulance
  - ../../xbartosj-ambulance

namespace: wac-hospital
